services:
  app:
    build:
      context: ./app
    image: anjaniops/task-tracker:latest
    container_name: task-tracker-app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - task-net
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: task-tracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - task-net
    restart: unless-stopped

networks:
  task-net:
    driver: bridge

volumes:
  pgdata:
